name: Build and Deploy React App

on:
  push:
    branches: [ "main" ]  # Se ejecuta cuando haces push a 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Usa una máquina virtual Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Descarga el código del repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Usa Node.js 20 (o la versión que necesites)

      - name: Install dependencies
        run: npm install  # Instala las dependencias

      - name: Build React App
        run: npm run build  # Ejecuta el build de React

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/  # Guarda la carpeta 'build' como artefacto