name: React Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Instalar dependencias
      run: npm ci
    
    - name: Ejecutar pruebas
      run: npm test -- --passWithNoTests
    
    - name: Construir proyecto
      run: npm run build
    
    - name: Guardar artefactos de build
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: build/